/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.auth;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
/**
 *
 * @author Siti Amalia Putri
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Flip & Match - Admin Menu");

        java.net.URL logoURL = getClass().getResource("logo-match.png");
        if (logoURL != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(logoURL);
            java.awt.Image scaledImage = icon.getImage().getScaledInstance(64, 64, java.awt.Image.SCALE_SMOOTH);
            setIconImage(scaledImage);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnKelolaTheme = new javax.swing.JButton();
        btnKelolaLevel = new javax.swing.JButton();
        btnKelolaScore = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnKelolaUser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("Selamat Datang Admin!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        btnKelolaTheme.setBackground(new java.awt.Color(102, 51, 0));
        btnKelolaTheme.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnKelolaTheme.setForeground(new java.awt.Color(255, 255, 255));
        btnKelolaTheme.setText("Kelola Tema");
        btnKelolaTheme.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKelolaTheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKelolaThemeMouseClicked(evt);
            }
        });
        btnKelolaTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaThemeActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 190, 40));

        btnKelolaLevel.setBackground(new java.awt.Color(102, 51, 0));
        btnKelolaLevel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnKelolaLevel.setForeground(new java.awt.Color(255, 255, 255));
        btnKelolaLevel.setText("Kelola Level");
        btnKelolaLevel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKelolaLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKelolaLevelMouseClicked(evt);
            }
        });
        btnKelolaLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaLevelActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 190, 40));

        btnKelolaScore.setBackground(new java.awt.Color(102, 51, 0));
        btnKelolaScore.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnKelolaScore.setForeground(new java.awt.Color(255, 255, 255));
        btnKelolaScore.setText("Kelola Score");
        btnKelolaScore.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKelolaScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKelolaScoreMouseClicked(evt);
            }
        });
        btnKelolaScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaScoreActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 190, 40));

        btnLogout.setBackground(new java.awt.Color(204, 0, 0));
        btnLogout.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 180, 40));

        btnKelolaUser.setBackground(new java.awt.Color(102, 51, 0));
        btnKelolaUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnKelolaUser.setForeground(new java.awt.Color(255, 255, 255));
        btnKelolaUser.setText("Kelola User");
        btnKelolaUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKelolaUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKelolaUserMouseClicked(evt);
            }
        });
        btnKelolaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 187, 41));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-kelolascore1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 187, 143));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-kelolauser.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 187, 143));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-kelolatema.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 187, 143));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-kelolalevel.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 187, 143));

        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg2.png"))); // NOI18N
        jPanel1.add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKelolaThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaThemeActionPerformed
        // TODO add your handling code here:
        new app.theme.FormTheme().setVisible(true);
    }//GEN-LAST:event_btnKelolaThemeActionPerformed

    private void btnKelolaThemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKelolaThemeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelolaThemeMouseClicked

    private void btnKelolaLevelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKelolaLevelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelolaLevelMouseClicked

    private void btnKelolaLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaLevelActionPerformed
        // TODO add your handling code here:
        new app.level.DashboardLevel().setVisible(true);
    }//GEN-LAST:event_btnKelolaLevelActionPerformed

    private void btnKelolaScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKelolaScoreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelolaScoreMouseClicked

    private void btnKelolaScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaScoreActionPerformed
        // TODO add your handling code here:
        new app.score.ShowScore().setVisible(true);
    }//GEN-LAST:event_btnKelolaScoreActionPerformed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int opsi = javax.swing.JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        if (opsi == javax.swing.JOptionPane.YES_OPTION) {
            new app.auth.LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnKelolaUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKelolaUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelolaUserMouseClicked

    private void btnKelolaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaUserActionPerformed
        // TODO add your handling code here:
        new app.user.FormUser().setVisible(true);
    }//GEN-LAST:event_btnKelolaUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKelolaLevel;
    private javax.swing.JButton btnKelolaScore;
    private javax.swing.JButton btnKelolaTheme;
    private javax.swing.JButton btnKelolaUser;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBg;
    // End of variables declaration//GEN-END:variables
}
