/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.score;
 
import java.awt.Image;
import javax.swing.ImageIcon;
 
/**
 *
 * @author ASUS
 */
public class FormScore extends javax.swing.JFrame {
 
    // Membuat objek 'scoreDAO' dari class ScoreDAO
    // Objek ini berfungsi sebagai perantara untuk mengambil/menyimpan data ke database
    private ScoreDAO scoreDAO = new ScoreDAO();
    private int idLevel;
    // Menyimpan ID level yang sedang aktif
 
    /**
     * Creates new form FormScore
     */
    // Constructor ini akan dipanggil saat jendela FormScore baru dibuat
    // Untuk mengirim data hasil game (menang/kalah, langkah, waktu, skor, level) ke sini
    public FormScore(boolean win, int moves, int timeLeft, int score, int idLevel) {
        initComponents(); // Menyiapkan komponen visual yang tampil di layar kayak (tombol, label, tabel)
        this.setLocationRelativeTo(null); // Agar layarnya di tengah
        this.idLevel = idLevel; // Untuk menyimpan nilai idLevel dari constructor
 
        // Mengisi tulisan di label sesuai data yang diterima
        lblUcapan.setText(win ? "Selamat! Kamu Menang" : "Waktu Habis!");
        lblmoves.setText("Moves: " + moves);
        lbltimeleft.setText("Time left: " + timeLeft + "s");
        lblskor.setText("Score: " + score);
        lbllevel.setText("Level " + idLevel);
 
        setTitle("Flip & Match");
 
        java.net.URL logoURL = getClass().getResource("logo-match.png");
 
        if (logoURL != null) {
            ImageIcon icon = new ImageIcon(logoURL);
            Image scaledImage = icon.getImage().getScaledInstance(64, 64, Image.SCALE_SMOOTH);
            setIconImage(scaledImage);
        }
 
        muatDataTabel(); // Memanggil fungsi untuk menampilkan top 5 ke tabel
    }
 
    // Fungsi untuk menampilkan data ke dalam tabel
    public void muatDataTabel() {
        // Membuat objek 'model' dari class DefaultTableModel
        // Objek ini bertugas mengatur kolom dan baris data pada tabel
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        // Menambahkan kolom
        model.addColumn("Peringkat");
        model.addColumn("Nama Pemain");
        model.addColumn("Level");
        model.addColumn("Skor");
        model.addColumn("Tanggal");
 
        top5table.setModel(model); // Untuk menghubungkan data ke tabel
        top5table.setDefaultEditor(Object.class, null); // Membuat tabel tidak bisa diketik manual
 
        // Digunakan untuk menyesuaikan ukuran column
        top5table.getColumnModel().getColumn(0).setPreferredWidth(80);
        top5table.getColumnModel().getColumn(1).setPreferredWidth(200);
        top5table.getColumnModel().getColumn(2).setPreferredWidth(120);
        top5table.getColumnModel().getColumn(3).setPreferredWidth(80);
        top5table.getColumnModel().getColumn(4).setPreferredWidth(150);
 
        // Digunakan untuk mengambil daftar skor dari database
        java.util.List<Score> dataScore = scoreDAO.getTop5(idLevel);
        // Untuk membuat urutan peringkat
        String[] medali = {"1", "2", "3", "4", "5"};
        int i = 0;
        // Melakukan perulangan untuk setiap data 'Score' yang ditemukan
        for (Score s : dataScore) {
            // Memasukkan data ke dalam baris tabel
            model.addRow(new Object[]{
                medali[i++],
                s.getNamaLengkap(),
                s.getNamaLevel(),
                s.getSkor(),
                s.getTanggalMain()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        top5table = new javax.swing.JTable();
        btncontinue = new javax.swing.JButton();
        lblUcapan = new javax.swing.JLabel();
        lblmoves = new javax.swing.JLabel();
        lbltimeleft = new javax.swing.JLabel();
        lblskor = new javax.swing.JLabel();
        lblleadborad = new javax.swing.JLabel();
        lbllevel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top5table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(top5table);

        btncontinue.setBackground(new java.awt.Color(102, 51, 0));
        btncontinue.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btncontinue.setForeground(new java.awt.Color(255, 255, 255));
        btncontinue.setText("Continue");
        btncontinue.setActionCommand("btnContinue");
        btncontinue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncontinue.addActionListener(this::btncontinueActionPerformed);

        lblUcapan.setBackground(new java.awt.Color(204, 255, 204));
        lblUcapan.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblUcapan.setText("Ucapan");

        lblmoves.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblmoves.setForeground(new java.awt.Color(102, 51, 0));
        lblmoves.setText("Moves:");

        lbltimeleft.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lbltimeleft.setForeground(new java.awt.Color(102, 51, 0));
        lbltimeleft.setText("Time left:");

        lblskor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblskor.setForeground(new java.awt.Color(102, 51, 0));
        lblskor.setText("Score");

        lblleadborad.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblleadborad.setText("Leaderboard Top 5");

        lbllevel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lbllevel.setForeground(new java.awt.Color(0, 153, 0));
        lbllevel.setText("Level Mudah");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblleadborad)
                        .addGap(334, 334, 334)
                        .addComponent(lbllevel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmoves)
                    .addComponent(lbltimeleft)
                    .addComponent(lblskor))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUcapan)
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btncontinue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblUcapan)
                .addGap(34, 34, 34)
                .addComponent(lblmoves)
                .addGap(6, 6, 6)
                .addComponent(lbltimeleft)
                .addGap(6, 6, 6)
                .addComponent(lblskor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblleadborad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbllevel)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncontinue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Aksi saat tombol "Continue" diklik
    private void btncontinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontinueActionPerformed
        // TODO add your handling code here:
        // Untuk pindah ke layar pilih lavel
        app.auth.PilihLevel menu = new app.auth.PilihLevel();
        menu.setVisible(true); // Menampilkan layar baru
        this.dispose(); // Menutup layar skor
    }//GEN-LAST:event_btncontinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Baris ini digunakan untuk menjalankan halaman saya
        java.awt.EventQueue.invokeLater(() -> new FormScore(true, 0, 0, 0, 0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncontinue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUcapan;
    private javax.swing.JLabel lblleadborad;
    private javax.swing.JLabel lbllevel;
    private javax.swing.JLabel lblmoves;
    private javax.swing.JLabel lblskor;
    private javax.swing.JLabel lbltimeleft;
    private javax.swing.JTable top5table;
    // End of variables declaration//GEN-END:variables
}
