/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.score;

/**
 *
 * @author ASUS
 */
public class FormScore extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormScore.class.getName());
    private ScoreDAO scoreDAO = new ScoreDAO();
    private int idLevel;

    /**
     * Creates new form FormScore
     */
    public FormScore(boolean win, int moves, int timeLeft, int score, int idLevel) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idLevel = idLevel;

        lblUcapan.setText(win ? "Selamat! Kamu Menang" : "Waktu Habis!");
        lblmoves.setText("Moves: " + moves);
        lbltimeleft.setText("Time left: " + timeLeft + "s");
        lblskor.setText("Score: " + score);
        lbllevel.setText("Level " + idLevel);

        muatDataTabel();
    }

    public void muatDataTabel() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("Peringkat");
        model.addColumn("Nama Pemain");
        model.addColumn("Level");
        model.addColumn("Skor");
        model.addColumn("Tanggal");

        top5table.setModel(model);
        top5table.setDefaultEditor(Object.class, null); // non-editable

        top5table.getColumnModel().getColumn(0).setPreferredWidth(80);
        top5table.getColumnModel().getColumn(1).setPreferredWidth(200);
        top5table.getColumnModel().getColumn(2).setPreferredWidth(120);
        top5table.getColumnModel().getColumn(3).setPreferredWidth(80);
        top5table.getColumnModel().getColumn(4).setPreferredWidth(150);

        java.util.List<Score> dataScore = scoreDAO.getTop5(idLevel);
        String[] medali = {"1", "2", "3", "4", "5"};
        int i = 0;
        for (Score s : dataScore) {
            model.addRow(new Object[]{
                medali[i++],
                s.getNamaLengkap(),
                s.getNamaLevel(),
                s.getSkor(),
                s.getTanggalMain()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        top5table = new javax.swing.JTable();
        btncontinue = new javax.swing.JButton();
        lblUcapan = new javax.swing.JLabel();
        lblmoves = new javax.swing.JLabel();
        lbltimeleft = new javax.swing.JLabel();
        lblskor = new javax.swing.JLabel();
        lblleadborad = new javax.swing.JLabel();
        lbllevel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        top5table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(top5table);

        btncontinue.setBackground(new java.awt.Color(102, 51, 0));
        btncontinue.setForeground(new java.awt.Color(255, 255, 255));
        btncontinue.setText("Continue");
        btncontinue.setActionCommand("btnContinue");
        btncontinue.addActionListener(this::btncontinueActionPerformed);

        lblUcapan.setBackground(new java.awt.Color(204, 255, 204));
        lblUcapan.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblUcapan.setText("Ucapan");

        lblmoves.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblmoves.setText("Moves:");

        lbltimeleft.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lbltimeleft.setText("Time left:");

        lblskor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblskor.setText("Score");

        lblleadborad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblleadborad.setText("Leaderboard Top 5");

        lbllevel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lbllevel.setText("Level Mudah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmoves)
                    .addComponent(lblskor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblleadborad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbllevel))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbltimeleft)
                    .addComponent(lblUcapan))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(btncontinue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblUcapan)
                .addGap(30, 30, 30)
                .addComponent(lblmoves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltimeleft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblskor)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllevel)
                    .addComponent(lblleadborad, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncontinue)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncontinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontinueActionPerformed
        // TODO add your handling code here:
        app.auth.MenuPemain menu = new app.auth.MenuPemain();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncontinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new FormScore(true, 3, 53, 715, 1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncontinue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUcapan;
    private javax.swing.JLabel lblleadborad;
    private javax.swing.JLabel lbllevel;
    private javax.swing.JLabel lblmoves;
    private javax.swing.JLabel lblskor;
    private javax.swing.JLabel lbltimeleft;
    private javax.swing.JTable top5table;
    // End of variables declaration//GEN-END:variables
}
