/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.score;

import app.auth.MenuAdmin;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aziza putri amelia
 */
public class ShowScore extends javax.swing.JFrame {
    
    // Untuk mencatat error
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShowScore.class.getName());

    /**
     * Creates new form ShowScore
     */
    
    private DefaultTableModel model; // Model untuk mengatur struktur tabel
    private ScoreDAO scoreDAO; // Atribut untuk komunikasi dengan database

    public ShowScore() {
        // Menggunakan komponen gui
        initComponents();

              setTitle("Flip & Match");

        java.net.URL logoURL = getClass().getResource("logo-match.png");

        if (logoURL != null) {
            ImageIcon icon = new ImageIcon(logoURL);
            // Resize ke 64x64
            Image scaledImage = icon.getImage().getScaledInstance(64, 64, Image.SCALE_SMOOTH);
            setIconImage(scaledImage);
        }
        
        // Untuk membuat objek baru
        scoreDAO = new ScoreDAO();

        // Buat header tabel
        model = new DefaultTableModel();
        model.addColumn("ID Score");
        model.addColumn("Nama User");
        model.addColumn("Level");
        model.addColumn("Skor");
        model.addColumn("Tanggal Main");

        tabelDataScore.setModel(model);

        // Memuat data dari database ke tabel saat form pertama kali dibuka
        loadDataScore();
    }

    // Method untuk mengambil data dari database dan menampilkannya ke tabel.
     private void loadDataScore() {

         // Kosongkan tabel sebelum diisi data baru
        model.setRowCount(0);
        // Untuk mengambil score ke dalam list
        List<Score> list = scoreDAO.getAllScore();
        for (Score s : list) {
            // Buat ngambil data dari tabelnya
            Object[] row = {
                s.getIdScore(),
                s.getNamaLengkap(),
                s.getNamaLevel(),
                s.getSkor(),
                s.getTanggalMain()
            };
            // Untuk menambahkan row
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataScore = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/arrowfiks.png"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(111, 53));
        jLabel9.setMinimumSize(new java.awt.Dimension(111, 53));
        jLabel9.setPreferredSize(new java.awt.Dimension(111, 53));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 60, 40));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Data Score User");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, 30));

        tabelDataScore.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tabelDataScore.setForeground(new java.awt.Color(102, 51, 0));
        tabelDataScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDataScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataScoreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataScore);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 790, 400));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Kelola Score");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 220, -1));

        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg2.png"))); // NOI18N
        jPanel1.add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        // Untuk pindah ke halaman menu admin
        new MenuAdmin().setVisible(true);
        // Untuk menutup halaman sekarang
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void tabelDataScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataScoreMouseClicked
        // TODO add your handling code here:
        // Untuk memilih baris data dari tabel yang diklik
        int row = tabelDataScore.getSelectedRow();

        if (row != -1) {
            // Untuk mengambil nilainya
            String idScore = model.getValueAt(row, 0).toString();
            String namaUser = model.getValueAt(row, 1).toString();
            String level = model.getValueAt(row, 2).toString();
            String skor = model.getValueAt(row, 3).toString();
            String tanggal = model.getValueAt(row, 4).toString();

            // Untuk menampilakn nilainya
            System.out.println("ID Score : " + idScore);
            System.out.println("Nama User : " + namaUser);
            System.out.println("Level : " + level);
            System.out.println("Skor : " + skor);
            System.out.println("Tanggal : " + tanggal);
        }
    }//GEN-LAST:event_tabelDataScoreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ShowScore().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBg;
    private javax.swing.JTable tabelDataScore;
    // End of variables declaration//GEN-END:variables
}
