/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.level;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nugih
 */
public class DashboardLevel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardLevel.class.getName());

    /**
     * Creates new form DashboardLevel
     */
    
    //instansiasi DAO
    private LevelDAO levelDAO = new LevelDAO();
    
    public DashboardLevel() {
        initComponents();
        this.setLocationRelativeTo(null); // biar di tengah layar
        muatDataTabel(); // Panggil fungsi muat data saat aplikasi berjalan
    }
    
    
    public void muatDataTabel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Level");
        model.addColumn("Tema Kartu"); 
        model.addColumn("Nama Level");
        model.addColumn("Baris");
        model.addColumn("Kolom");
        model.addColumn("Waktu (Detik)");

        jTable1.setModel(model);

        java.util.List<Level> dataLevel = levelDAO.getAll();
        for (Level lvl : dataLevel) {
            model.addRow(new Object[]{
                lvl.getIdLevel(),
                lvl.getNamaTheme(), 
                lvl.getNamaLevel(),
                lvl.getBaris(),
                lvl.getKolom(),
                lvl.getWaktuDetik()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulDaftarLevel = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnTambahLevel = new javax.swing.JButton();
        btnEditLevel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudulDaftarLevel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudulDaftarLevel.setText("Daftar Level");
        getContentPane().add(lblJudulDaftarLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 160, 30));

        btnTambahLevel.setBackground(new java.awt.Color(153, 255, 153));
        btnTambahLevel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnTambahLevel.setText("Tambah");
        btnTambahLevel.addActionListener(this::btnTambahLevelActionPerformed);
        getContentPane().add(btnTambahLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 160, 30));

        btnEditLevel.setBackground(new java.awt.Color(174, 137, 23));
        btnEditLevel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnEditLevel.setText("Edit");
        btnEditLevel.addActionListener(this::btnEditLevelActionPerformed);
        getContentPane().add(btnEditLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 160, 30));

        jTable1.setBackground(new java.awt.Color(199, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahLevelActionPerformed
        // TODO add your handling code here:
        FormLevelInput formInput = new FormLevelInput(this);
        formInput.setVisible(true);
    }//GEN-LAST:event_btnTambahLevelActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int barisTerpilih = jTable1.getSelectedRow();
        
        if (barisTerpilih >= 0) {
            // Ambil ID dari kolom pertama (indeks 0)
            int idLevel = (int) jTable1.getValueAt(barisTerpilih, 0);
            
            int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus level ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
            
            if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
                if (levelDAO.delete(idLevel)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
                    muatDataTabel(); // Segarkan tabel
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih baris pada tabel terlebih dahulu.", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLevelActionPerformed
        // TODO add your handling code here
        int barisTerpilih = jTable1.getSelectedRow();
        
        if (barisTerpilih >= 0) {
            java.util.List<Level> dataLevel = levelDAO.getAll();
            Level lvlTerpilih = dataLevel.get(barisTerpilih);
            
            FormLevelInput formInput = new FormLevelInput(this);
            formInput.setModeEdit(
                lvlTerpilih.getIdLevel(), 
                lvlTerpilih.getIdTheme(), 
                lvlTerpilih.getNamaLevel(), 
                lvlTerpilih.getBaris(), 
                lvlTerpilih.getKolom(), 
                lvlTerpilih.getWaktuDetik()
            );
            formInput.setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih baris pada tabel terlebih dahulu untuk diedit.", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditLevelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardLevel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditLevel;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambahLevel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblJudulDaftarLevel;
    // End of variables declaration//GEN-END:variables
}
