/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.level;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author nugih
 */
public class FormLevelInput extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLevelInput.class.getName());

    /**
     * Creates new form FormLevel1
     */
    
    // Instansiasi DAO dan referensi Dasbor
    private LevelDAO levelDAO = new LevelDAO();
    private app.theme.ThemeDAO themeDAO = new app.theme.ThemeDAO(); 
    private DashboardLevel dashboardUtama;
    private int editIdLevel = -1;
    
    // ubah konstruktor bawaan untuk menerima referensi Dasbor
    public FormLevelInput(DashboardLevel dashboard) {
        this.dashboardUtama = dashboard;
        initComponents();
        this.setLocationRelativeTo(null);
        populateThemeComboBox(); 
    }
    
    public FormLevelInput() {
        initComponents();
              setTitle("Flip & Match");

        java.net.URL logoURL = getClass().getResource("logo-match.png");

        if (logoURL != null) {
            ImageIcon icon = new ImageIcon(logoURL);
            // Resize ke 64x64
            Image scaledImage = icon.getImage().getScaledInstance(64, 64, Image.SCALE_SMOOTH);
            setIconImage(scaledImage);
        }
    }
    
    private void populateThemeComboBox() {
        cbTheme.removeAllItems();
        java.util.List<app.theme.theme> themes = themeDAO.getAllTheme();
        for (app.theme.theme t : themes) {
            cbTheme.addItem(new ThemeItem(t.getIdTheme(), t.getNamaTheme()));
        }
    }

    // Fungsi untuk mengubah form menjadi mode Edit dan mengisi kolom dengan data lama
    public void setModeEdit(int id, int idTheme, String nama, int baris, int kolom, int waktu) {
        this.editIdLevel = id;
        txtNamaLevel.setText(nama);
        txtJumlahBaris.setText(String.valueOf(baris));
        txtJumlahKolom.setText(String.valueOf(kolom));
        txtWaktu.setText(String.valueOf(waktu));
        lblJudulBuatLevel.setText("Edit Level");
        
        for (int i = 0; i < cbTheme.getItemCount(); i++) {
            ThemeItem item = (ThemeItem) cbTheme.getItemAt(i);
            if (item.id == idTheme) {
                cbTheme.setSelectedIndex(i);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamaLevel = new javax.swing.JLabel();
        lblJudulBuatLevel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtJumlahBaris = new javax.swing.JTextField();
        txtNamaLevel = new javax.swing.JTextField();
        txtJumlahKolom = new javax.swing.JTextField();
        txtWaktu = new javax.swing.JTextField();
        btnSimpanLevel = new javax.swing.JButton();
        lblCbTema = new javax.swing.JLabel();
        lblJumlahKolom = new javax.swing.JLabel();
        lblJumlahBaris = new javax.swing.JLabel();
        cbTheme = new javax.swing.JComboBox<>();
        lblWaktu1 = new javax.swing.JLabel();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamaLevel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblNamaLevel.setText("Nama Level:");
        getContentPane().add(lblNamaLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, 30));

        lblJudulBuatLevel.setBackground(new java.awt.Color(204, 255, 204));
        lblJudulBuatLevel.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblJudulBuatLevel.setForeground(new java.awt.Color(102, 51, 0));
        lblJudulBuatLevel.setText("Tambah Level");
        getContentPane().add(lblJudulBuatLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 250, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/arrowfiks.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(111, 53));
        jLabel2.setMinimumSize(new java.awt.Dimension(111, 53));
        jLabel2.setPreferredSize(new java.awt.Dimension(111, 53));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 60, 40));

        txtJumlahBaris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtJumlahBaris.addActionListener(this::txtJumlahBarisActionPerformed);
        getContentPane().add(txtJumlahBaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 270, 30));

        txtNamaLevel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNamaLevel.addActionListener(this::txtNamaLevelActionPerformed);
        getContentPane().add(txtNamaLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 270, 30));

        txtJumlahKolom.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtJumlahKolom.addActionListener(this::txtJumlahKolomActionPerformed);
        getContentPane().add(txtJumlahKolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 270, 30));

        txtWaktu.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtWaktu.addActionListener(this::txtWaktuActionPerformed);
        getContentPane().add(txtWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 270, 30));

        btnSimpanLevel.setBackground(new java.awt.Color(0, 204, 102));
        btnSimpanLevel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnSimpanLevel.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanLevel.setText("Tambah");
        btnSimpanLevel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSimpanLevel.addActionListener(this::btnSimpanLevelActionPerformed);
        getContentPane().add(btnSimpanLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 420, 30));

        lblCbTema.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblCbTema.setText("Tema:");
        getContentPane().add(lblCbTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, 30));

        lblJumlahKolom.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblJumlahKolom.setText("Jumlah Kolom:");
        getContentPane().add(lblJumlahKolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, 30));

        lblJumlahBaris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblJumlahBaris.setText("Jumlah Baris:");
        getContentPane().add(lblJumlahBaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, 30));

        cbTheme.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cbTheme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTheme.addActionListener(this::cbThemeActionPerformed);
        getContentPane().add(cbTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 270, 30));

        lblWaktu1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblWaktu1.setText("Waktu:");
        getContentPane().add(lblWaktu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, 30));

        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg2.png"))); // NOI18N
        getContentPane().add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahBarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBarisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBarisActionPerformed

    private void txtNamaLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaLevelActionPerformed

    private void txtJumlahKolomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahKolomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahKolomActionPerformed

    private void txtWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWaktuActionPerformed

    private void btnSimpanLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanLevelActionPerformed
        // TODO add your handling code here:
        try {
            ThemeItem selectedTheme = (ThemeItem) cbTheme.getSelectedItem();
            if (selectedTheme == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Silakan tentukan tema terlebih dahulu.", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int idTheme = selectedTheme.id;
            String nama = txtNamaLevel.getText();
            int baris = Integer.parseInt(txtJumlahBaris.getText());
            int kolom = Integer.parseInt(txtJumlahKolom.getText());
            int waktu = Integer.parseInt(txtWaktu.getText());

            if ((baris * kolom) % 2 != 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Perkalian Baris dan Kolom harus menghasilkan angka genap.", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            Level levelData = new Level(idTheme, nama, baris, kolom, waktu);
            boolean berhasil = false;

            if (editIdLevel == -1) {
                berhasil = levelDAO.insert(levelData);
            } else {
                levelData.setIdLevel(editIdLevel);
                berhasil = levelDAO.update(levelData);
            }

            if (berhasil) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data level berhasil disimpan.");
                if (dashboardUtama != null) {
                    dashboardUtama.muatDataTabel();
                }
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke basis data.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Input Baris, Kolom, dan Waktu harus berupa angka bulat.", "Format Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanLevelActionPerformed

    private void cbThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbThemeActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new DashboardLevel().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLevelInput().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpanLevel;
    private javax.swing.JComboBox<Object> cbTheme;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBg;
    private javax.swing.JLabel lblCbTema;
    private javax.swing.JLabel lblJudulBuatLevel;
    private javax.swing.JLabel lblJumlahBaris;
    private javax.swing.JLabel lblJumlahKolom;
    private javax.swing.JLabel lblNamaLevel;
    private javax.swing.JLabel lblWaktu1;
    private javax.swing.JTextField txtJumlahBaris;
    private javax.swing.JTextField txtJumlahKolom;
    private javax.swing.JTextField txtNamaLevel;
    private javax.swing.JTextField txtWaktu;
    // End of variables declaration//GEN-END:variables
}

class ThemeItem {
    int id;
    String name;
    public ThemeItem(int id, String name) { this.id = id; this.name = name; }
    @Override public String toString() { return name; }
}
