/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.level;

/**
 *
 * @author nugih
 */
public class FormLevelInput extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLevelInput.class.getName());

    /**
     * Creates new form FormLevel1
     */
    
    // Instansiasi DAO dan referensi Dasbor
    private LevelDAO levelDAO = new LevelDAO();
    private DashboardLevel dashboardUtama;
    
    // ubah konstruktor bawaan untuk menerima referensi Dasbor
    public FormLevelInput(DashboardLevel dashboard) {
        this.dashboardUtama = dashboard;
        initComponents();
        this.setLocationRelativeTo(null); // Tampilkan di tengah layar
    }
    
    public FormLevelInput() {
        initComponents();
    }
    
    // Variabel untuk menyimpan ID saat mode edit.
    private int editIdLevel = -1; 

    // Fungsi untuk mengubah form menjadi mode Edit dan mengisi kolom dengan data lama
    public void setModeEdit(int id, String nama, int baris, int kolom, int waktu) {
        this.editIdLevel = id;
        txtNamaLevel.setText(nama);
        txtJumlahBaris.setText(String.valueOf(baris));
        txtJumlahKolom.setText(String.valueOf(kolom));
        txtWaktu.setText(String.valueOf(waktu));
        lblJudulBuatLevel.setText("Edit Level"); // Opsional: mengubah teks judul form
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamaLevel = new javax.swing.JLabel();
        txtJumlahBaris = new javax.swing.JTextField();
        txtNamaLevel = new javax.swing.JTextField();
        txtJumlahKolom = new javax.swing.JTextField();
        txtWaktu = new javax.swing.JTextField();
        btnSimpanLevel = new javax.swing.JButton();
        lblWaktu = new javax.swing.JLabel();
        lblJumlahKolom = new javax.swing.JLabel();
        lblJudulBuatLevel = new javax.swing.JLabel();
        lblJumlahBaris = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamaLevel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblNamaLevel.setText("Nama Level:");
        getContentPane().add(lblNamaLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        txtJumlahBaris.addActionListener(this::txtJumlahBarisActionPerformed);
        getContentPane().add(txtJumlahBaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 270, -1));

        txtNamaLevel.addActionListener(this::txtNamaLevelActionPerformed);
        getContentPane().add(txtNamaLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 270, -1));

        txtJumlahKolom.addActionListener(this::txtJumlahKolomActionPerformed);
        getContentPane().add(txtJumlahKolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 270, -1));

        txtWaktu.addActionListener(this::txtWaktuActionPerformed);
        getContentPane().add(txtWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 270, -1));

        btnSimpanLevel.setBackground(new java.awt.Color(153, 255, 153));
        btnSimpanLevel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnSimpanLevel.setText("SIMPAN");
        btnSimpanLevel.addActionListener(this::btnSimpanLevelActionPerformed);
        getContentPane().add(btnSimpanLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 240, 30));

        lblWaktu.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblWaktu.setText("Waktu:");
        getContentPane().add(lblWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        lblJumlahKolom.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblJumlahKolom.setText("Jumlah Kolom:");
        getContentPane().add(lblJumlahKolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        lblJudulBuatLevel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudulBuatLevel.setText("Buat Level");
        getContentPane().add(lblJudulBuatLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        lblJumlahBaris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblJumlahBaris.setText("Jumlah Baris:");
        getContentPane().add(lblJumlahBaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg.jpeg"))); // NOI18N
        lblBackground.setText("jLabel1");
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahBarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBarisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBarisActionPerformed

    private void txtNamaLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaLevelActionPerformed

    private void txtJumlahKolomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahKolomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahKolomActionPerformed

    private void txtWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWaktuActionPerformed

    private void btnSimpanLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanLevelActionPerformed
        // TODO add your handling code here:
        try {
            String nama = txtNamaLevel.getText();
            int baris = Integer.parseInt(txtJumlahBaris.getText());
            int kolom = Integer.parseInt(txtJumlahKolom.getText());
            int waktu = Integer.parseInt(txtWaktu.getText());

            if ((baris * kolom) % 2 != 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Perkalian Baris dan Kolom harus menghasilkan angka genap.", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            Level levelData = new Level(nama, baris, kolom, waktu);
            boolean berhasil = false;

            // Percabangan logika eksekusi DAO
            if (editIdLevel == -1) {
                // Mode Tambah Baru
                berhasil = levelDAO.insert(levelData);
            } else {
                // Mode Edit Data
                levelData.setIdLevel(editIdLevel); // Set ID yang akan diupdate
                berhasil = levelDAO.update(levelData);
            }

            if (berhasil) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data level berhasil disimpan.");
                if (dashboardUtama != null) {
                    dashboardUtama.muatDataTabel(); // Perbarui tabel dasbor
                }
                this.dispose(); // Tutup form
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke basis data.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Input Baris, Kolom, dan Waktu harus berupa angka bulat.", "Format Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanLevelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLevelInput().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpanLevel;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblJudulBuatLevel;
    private javax.swing.JLabel lblJumlahBaris;
    private javax.swing.JLabel lblJumlahKolom;
    private javax.swing.JLabel lblNamaLevel;
    private javax.swing.JLabel lblWaktu;
    private javax.swing.JTextField txtJumlahBaris;
    private javax.swing.JTextField txtJumlahKolom;
    private javax.swing.JTextField txtNamaLevel;
    private javax.swing.JTextField txtWaktu;
    // End of variables declaration//GEN-END:variables
}
